FROM node:20-alpine

WORKDIR /app

# Cài dependencies trước để cache
COPY package*.json ./
RUN npm install

# Copy source (dev thì chủ yếu mount volume)
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev_test"]
