import {
    DIARY,
    PATIENT_RECORD,
    BUY_HISTORY,
    INFORMATION,
    FOLLOW,
    PROVIDER,
    DOCTOR_OR_PHARMACIST,
    INDEX_DIARY,
    INDEX_PATIENT_RECORD,
    INDEX_BUY_HISTORY,
    INDEX_INFORMATION,
    INDEX_FOLLOW,
    INDEX_PROVIDER,
    INDEX_DOCTOR_OR_PHARMACIST,
} from './const';

export type selections_type =
    | typeof DIARY
    | typeof PATIENT_RECORD
    | typeof BUY_HISTORY
    | typeof INFORMATION
    | typeof FOLLOW
    | typeof PROVIDER
    | typeof DOCTOR_OR_PHARMACIST;

export type selections_index_type =
    | typeof INDEX_DIARY
    | typeof INDEX_PATIENT_RECORD
    | typeof INDEX_BUY_HISTORY
    | typeof INDEX_INFORMATION
    | typeof INDEX_FOLLOW
    | typeof INDEX_PROVIDER
    | typeof INDEX_DOCTOR_OR_PHARMACIST;

const _DIARY = DIARY;
const _PATIENT_RECORD = PATIENT_RECORD;
const _BUY_HISTORY = BUY_HISTORY;
const _INFORMATION = INFORMATION;
const _FOLLOW = FOLLOW;
const _PROVIDER = PROVIDER;
const _DOCTOR_OR_PHARMACIST = DOCTOR_OR_PHARMACIST;
export enum selections_enum {
    DIARY = _DIARY,
    PATIENT_RECORD = _PATIENT_RECORD,
    BUY_HISTORY = _BUY_HISTORY,
    INFORMATION = _INFORMATION,
    FOLLOW = _FOLLOW,
    PROVIDER = _PROVIDER,
    DOCTOR_OR_PHARMACIST = _DOCTOR_OR_PHARMACIST,
}

const _INDEX_DIARY = INDEX_DIARY;
const _INDEX_PATIENT_RECORD = INDEX_PATIENT_RECORD;
const _INDEX_BUY_HISTORY = INDEX_BUY_HISTORY;
const _INDEX_INFORMATION = INDEX_INFORMATION;
const _INDEX_FOLLOW = INDEX_FOLLOW;
const _INDEX_PROVIDER = INDEX_PROVIDER;
const _INDEX_DOCTOR_OR_PHARMACIST = INDEX_DOCTOR_OR_PHARMACIST;
export enum selections_index_enum {
    DIARY = _INDEX_DIARY,
    PATIENT_RECORD = _INDEX_PATIENT_RECORD,
    BUY_HISTORY = _INDEX_BUY_HISTORY,
    INFORMATION = _INDEX_INFORMATION,
    FOLLOW = _INDEX_FOLLOW,
    PROVIDER = _INDEX_PROVIDER,
    DOCTOR_OR_PHARMACIST = _INDEX_DOCTOR_OR_PHARMACIST,
}
